import os

RUN_DEBUG = True
RUN_USE_RELOADER = True
RUN_HOST = 'localhost'
RUN_PORT = 5000

DEBUG = True

TEMPLATES_AUTO_RELOAD = True
EXPLAIN_TEMPLATE_LOADING = True
JINJA_CACHE_SIZE = 0
LOGGER_NAME = "data-science"
VERSAO = 1