RUN_DEBUG = False
RUN_USE_RELOADER = False
RUN_HOST = 'localhost'
RUN_PORT = 5000

DEBUG = False

TEMPLATES_AUTO_RELOAD = False
EXPLAIN_TEMPLATE_LOADING = False
JINJA_CACHE_SIZE = 0
LOGGER_NAME = "data-science"
VERSAO = 1